[tool.poetry]
name = "java-sandbox"
version = "0.1.0"
description = ""
authors = ["Austin R. Scott <ars@austinrscott.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
